//Real Time 
//Grab all the contacts
GET https://assign1.onrender.com/contacts 
###
//grab one of the contacts by id
GET https://assign1.onrender.com/contacts/632e74c4f82c1783bd834839 
###
GET https://assign1.onrender.com/contacts/632e74c4f82c1783bd83483a 
###
GET https://assign1.onrender.com/contacts/632e74c4f82c1783bd83483b

### initial site
GET https://assign1.onrender.com/

//Locally
###
GET http://localhost:8080/contacts/
###
GET http://localhost:8080/contacts/632e74c4f82c1783bd834839
###
GET http://localhost:8080/contacts/632e74c4f82c1783bd83483a
###
GET http://localhost:8080/contacts/632e74c4f82c1783bd83483b
###