//Production
GET https://assign1.onrender.com/contacts 
###
GET https://assign1.onrender.com/contacts/632e74c4f82c1783bd834839 
###
GET https://assign1.onrender.com/contacts/632e74c4f82c1783bd83483a 
###
GET https://assign1.onrender.com/contacts/632e74c4f82c1783bd83483b

###
GET https://assign1.onrender.com/

//Locally
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/632e74c4f82c1783bd834839
###
GET http://localhost:8080/contacts/632e74c4f82c1783bd83483a
###
GET http://localhost:8080/contacts/632e74c4f82c1783bd83483b
###
//I cannot get any of these to work and I don't know why
//I think the problem is not in this file though